# Source: cscaler/templates/proxy-http-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cscaler-proxy
  labels:
    name: cscaler-proxy
    app: cscaler
    chart: "cscaler-0.0.1"
    release: "cscaler"
    heritage: "Helm"
spec:
  type: LoadBalancer
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    name: cscaler-proxy
    app: cscaler
    release: "cscaler"