# apiVersion: v1
# kind: Secret
# metadata:
#   name: votes-db-secret
# type: Opaque
# data:
#   redis_password: YWRtaW4=
# ---
# apiVersion: keda.k8s.io/v1alpha1
# kind: TriggerAuthentication
# metadata:
#   name: keda-trigger-auth-redis-secret
# spec:
#   secretTargetRef:
#   - parameter: password
#     name: votes-db-secret
#     key: redis_password
# ---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: external-scaledobject
spec:
  scaleTargetRef:
    deploymentName: cscaler-dummyapp
  triggers:
    - type: external
      metadata:
        # TODO: kubernetes service DNS below
        scalerAddress: {{ .Values.proxyGRPCSvcName }}.{{ .Release.Namespace }}:9090
        key1: value1
        key2: value2

