apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxyGRPCSvcName }}
  labels:
    app.kubernetes.io/name: cscaler
    app: cscaler
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: cscaler
