apiVersion: v1
kind: Service
metadata:
  name: cscaler-service
  labels:
    app.kubernetes.io/name: cscaler
    app: cscaler
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: cscaler
