apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.proxyDeployName }}
  labels:
    app: cscaler
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: cscaler-proxy
      app: {{ template "fullname" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        name: cscaler-proxy
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
    spec:
        serviceAccountName: cscaler-proxy
        containers:
        - name: {{ template "fullname" . }}
          image: "arschles/cscaler:latest"
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          - containerPort: 9090
          env:
          - name: "CSCALER_SCALER_ADDRESS"
            value: {{ .Values.proxyGRPCSvcName }}.{{ .Release.Namespace }}:{{ .Values.proxyGRPCSvcPort}}