apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxyGRPCSvcName }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Values.proxyGRPCSvcName }}
    app: cscaler
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    name: cscaler-proxy
    app: {{ template "fullname" . }}
    release: "{{ .Release.Name }}"