apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: cscaler-proxy
rules:
- apiGroups: ["", "apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["get", "watch", "list", create]
