apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxySvcName }}
  labels:
    app.kubernetes.io/name: cscaler
    app: cscaler
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: LoadBalancer
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8080
    # TODO: put this behind a different ClusterIP service
    - name: grpc-externalscaler
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app.kubernetes.io/name: cscaler
